
spring:
  application:
    name: livecat
  datasource:
    url: jdbc:sqlite:./database.db
    #    username: root
    #    password: root
    driver-class-name: org.sqlite.JDBC
server:
  port: 8889

livecat:
  proxy:
    enable: 0
    address: 127.0.0.1
    port: 7890